task: detection

num_classes: 2
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ../data/train
    ann_file: ../data/annotations/train_annotations_coco.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 1
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ../data/val
    ann_file: ../data/annotations/val_annotations_coco.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 1
  drop_last: False